version: '3.7'

services:
  nats:
    image: nats
    ports:
    - 4222:4222
    - 8222:8222

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: Admin
    volumes:
    - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017

  stan:
    image: nats-streaming
    ports:
    - 4223:4222
    - 8223:8222
    command: --store file --dir /var/stan/datastore --max_channels 0 --max_subs 0 --max_msgs 0 --max_bytes 0 --max_age 0s
    volumes:
    - stan-files:/var/stan/datastore

volumes:
  stan-files:
  mongodb: